version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SA
      - MONGO_INITDB_ROOT_PASSWORD=Abc@123
    networks:
      - common
  node: 
    container_name: node_server
    build:
    # Location to the Dockerfile
      context: .
      # Name of the Dockerfile
      dockerfile: ./Dockerfile
    ports:
    # host port:container port
      - 5000:5000
    volumes:
      - .:/app
    command: npm run server 
    networks:
    - common
    environment:
      PORT: 5000
      MONGO_URL: 'mongodb://mongo/test'
      NODE_ENV: 'development' 
    depends_on:
      - mongodb
networks:
  common:
      